spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/team2_activity}
    username: ${DB_USERNAME:team2}
    password: ${DB_PASSWORD:team2}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
