DROP TABLE IF EXISTS activity_package_items;
DROP TABLE IF EXISTS activity_package_viewers;
DROP TABLE IF EXISTS email_log_attachments;
DROP TABLE IF EXISTS email_log_types;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS activity_packages;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS email_logs;

CREATE TABLE activities (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    po_id VARCHAR(30),
    activity_author_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    activity_type VARCHAR(20) NOT NULL,
    activity_title VARCHAR(100) NOT NULL,
    activity_content CLOB,
    activity_priority VARCHAR(10),
    activity_schedule_from DATE,
    activity_schedule_to DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE contacts (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    writer_id BIGINT,
    contact_name VARCHAR(100) NOT NULL,
    contact_position VARCHAR(100),
    contact_email VARCHAR(255),
    contact_tel VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE email_logs (
    email_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    po_id VARCHAR(30),
    email_title VARCHAR(200) NOT NULL,
    email_recipient_name VARCHAR(100),
    email_recipient_email VARCHAR(255) NOT NULL,
    email_sender_id BIGINT NOT NULL,
    email_status VARCHAR(10) NOT NULL,
    email_sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE email_log_types (
    email_log_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_log_id BIGINT NOT NULL,
    email_doc_type VARCHAR(20) NOT NULL
);

CREATE TABLE email_log_attachments (
    email_log_attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_log_id BIGINT NOT NULL,
    email_attachment_filename VARCHAR(255) NOT NULL
);

CREATE TABLE activity_packages (
    package_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_title VARCHAR(100) NOT NULL,
    package_description CLOB,
    po_id VARCHAR(30),
    creator_id BIGINT NOT NULL,
    date_from DATE,
    date_to DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE activity_package_viewers (
    package_viewer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE activity_package_items (
    package_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL
);
